### ISSUE TITLE
Floodlight Cam 2 Pro

### ISSUE THREAD

**Issue by sluxtor** [samemory/homebridge-eufy-security#347]
_Originally posted by @JCSEA2019 in https://github.com/samemory/homebridge-eufy-security/discussions/288_

I saw this previous post without confirmation on whether there is currently support for the Floodlight Cam 2 Pro T8423?

If so does anyone have experience with the usability? Does it have live updating screenshots? Does the audio work with HK?

**Comment by schliemann** [comment]
@sluxtor 

I don't know. But as @lenoxys wrote in the other issue you are welcome to install the beta and see if it works.

There are so many eufy devices so we really don't know. The best guess is looking at bropats list of supported devices.

**Comment by sluxtor** [comment]
Thank you for the reply!

I would love to be able to test camera and the beta but I currently do not own it. Just trying to plan for the possibility that I may one day be using it.

I will surely post my findings if I do purchase the camera in the future.

**Comment by DolmensDude** [comment]
have two of these... this plugin raises two issues with these devices in the logfiles:

[2/5/2022, 11:02:06 AM] [EufySecurity] Exterior North looks station but it's not could imply some errors Type: 38
[2/5/2022, 11:02:06 AM] [EufySecurity] Exterior North has no battery

Exterior North being the name of one of my two cams.

In Home app, these two cams will continuously report that they are trying to arm.

do they work? yes, but there is apparently an issue in the underlying lib that is used by this plugin.

**Comment by lenoxys** [comment]
Are you using scheduling or GEO arming ?

**Comment by DolmensDude** [comment]
no, not using either. should I test the beta version for these?

I have 6 eufy motion sensors, going thru a HomeBase 2, 2 battery doorbell/cams , as well as 4 eufy native-HomeKit capable indoor cams. 

things are actually going okay other than what's noted above - these are still relatively new, so I'm not worried, but if it will help to test the beta? No prob!

**Comment by karesake** [comment]
Hi there 

Can any1 tell me that the Floodlight Cam 2 Pro is working in HomeKit with the Plugin ? Can i set the Lights separate on and off ?

**Comment by karesake** [comment]
Works like every Camera very slow, laggy and absolutly unusable!

**Comment by schliemann** [comment]
> Works like every Camera very slow, laggy and absolutly unusable!

We are still awaiting your PRs to fix these issues.

**Comment by schliemann** [comment]
> Is there any other HomeKit Camera Plugin ?

You could create your own if you refuse to fix bugs with PRs?

**Comment by karesake** [comment]
I think every user of this plugin has a camera installed. Due to the fact that Eufy does not produce any new cameras with HomeKit, it would be the most important thing for me as a developer to enable at least this feature.

Maybe I don't understand the problem either? The stream is set up immediately in the Eufy app. So there must be an address for the live stream somewhere. Why are you still trying to access the stream over the network?

For example, the Eufy RTSP stream works INSTANTLY with Camera UI! And even with HomeKit Secure Video. The only problem is that the camera goes into standby after two minutes. RTSP is also possible with FFMPEG, you just need something that wakes up the camera as soon as you click on the stream.

So theoretically it would be the better solution to integrate the local RTSP stream. The only problem is that the camera switches to standby after two minutes and even then the stream is no longer accessible. RTSP is also possible with FFMPEG. As already mentioned, Camera UI also offers HKSV. So, technically, we would need something that activates the camera when you click on the stream (as before) only then

**Comment by lenoxys** [comment]
I would love to have HKSV. We're doing this during our free time and it takes time to port this into the plugin. In addition, we have to fix issue introduced by Eufy on their App 4.0, this is consuming a lot so we can only focus on small enhanced feature as of today. To be honest, I use Camera UI at this moment with RTSP for HKSV in addition with this plugin to get the alarm stuff on HK.

**Comment by karesake** [comment]
But your Livestream also goes offline with Camera UI ? But that would be exactly what you could easily do. A mixture of both. The plugin to wake up the camera and then access the RTSP stream. Whether that's with FFMPEG or Camera UI doesn't really matter.

**Comment by lenoxys** [comment]
I don't have offline issue on Camera UI (been 5min and livestream works perfectly) and I've tested on the camera the most far from wifi.

Camera UI rely on FFMPEG behind the scene.

Again it's a matter of having free time to get in. Which is rare ATM.

**Comment by DolmensDude** [comment]
I too find that the streams report as offline in the Home app, or ATV. Retrying does seem to bring it back after a few tries, but sometimes that won't work either.  Restarting HomeBridge sometimes helps...

I installed the beta yesterday and tried that. No streams worked. I received the other error messages documented by someone else here, so I reverted back to v1.08 and I got my streams back. 

Eufy seems to be all over the place architecturally right now. Floodlight Cam Pro 2's that do not support homekit, but also do not link back to Homebase 2 either. Homebase 2 shows no camera's to share with HomeKit integration, even though I have two battery doorbells and 6 motion sensors...

The native HomeKit pan and tilt cams *do* show up in the Home app and ATV.  

One thing is certain, my wifi is tiptop. The problem lies elsewhere.

**Comment by fullphat** [comment]
@karesake The T8420 Floodlight camera doesn't support RTSP so I need this plugin as Camera.ui (and ffmpeg) won't help me here.  

Just pointing out a critical use-case for this plugin you might not be aware of.

The guys here are doing a great job, and all for free too.

**Comment by karesake** [comment]
The old one doesn't. But the new and all new Eufy products have it.

No one says that the current path should not continue to be supported.

Still, it would be great to be able to use RTSP streams if the camera
